### ISSUE TITLE
[Improve] Add hightlight color variable in vue template

### ISSUE THREAD

**Issue by kytosai** [icao/electron-vue#1]
Add hightlight color variable in vue template

Current:
![alt text](https://i.imgur.com/63HHtYh.png)

Example horizon theme
![alt text](https://i.imgur.com/8WlGHDY.png)

**Comment by icao** [comment]
Hi @KytoSai , I have reviewed the suggestion you comment, I will be working on it to soon upload a new correction.
Thanks for the feedback.

**Comment by icao** [comment]
Hi @KytoSai, I am finally taking up the project and I have been working on improving the visualization of the variables (objects, object properties, directives and more details). I will soon upload a new version 🤓.

**Comment by kytosai** [comment]
> Hi @KytoSai, I am finally taking up the project and I have been working on improving the visualization of the variables (objects, object properties, directives and more details). I will soon upload a new version 🤓.

Thank you ^^ !!!!

**Comment by comphonia** [comment]
@kytosai How did you get your render lines to show? 
Please see #4 Thanks!
