### ISSUE TITLE
Theme does not render indent guides

### ISSUE THREAD

**Issue by comphonia** [icao/electron-vue#4]
What I'm expecting
![image](https://user-images.githubusercontent.com/37687869/124116346-7b7ee380-da34-11eb-8243-9a4f78f14d65.png)

What I'm getting
![image](https://user-images.githubusercontent.com/37687869/124116403-8afe2c80-da34-11eb-93ae-ddbd944130cf.png)

I have my `Editor: Render Indent Guides` settings checked.
Please let me know how I can resolve this. Excellent theme BTW!

**Comment by icao** [comment]
@comphonia Sorry, I just saw your message.
What language are you working in? 🤔
Let me know and I will be reviewing the problem to work on a solution to correct it, thanks for keeping an eye on it. 🤓

**Comment by comphonia** [comment]
![electron-vue](https://user-images.githubusercontent.com/37687869/137325788-7351bbfb-7e5e-4fdf-94c4-38936b070656.gif)

@icao  It's an editor-wide issue for me, only for this theme.
I use [Guides Extension](https://marketplace.visualstudio.com/items?itemName=spywhere.guides) to get around it though

**Comment by icao** [comment]
@comphonia I have good news 😁, I just generated a new update with the change. 💫
Thanks for the review, at the time I thought it was the right thing to do, but today I think the guide is necessary.
Enjoy the upgrade 🐱‍👓, I hope you will give Electron Vue Theme another chance. 🙏

![image](https://user-images.githubusercontent.com/5899969/137456913-4fa3825e-4f2e-46a7-8b44-8fc457d1d2bf.png)


**NOTE**: Only you neeed update the theme and reload your VSCODE

**Comment by comphonia** [comment]
@icao Works great! Thanks for the quick fix. And Electron Vue Darker is already my default ☺

**Comment by icao** [comment]
This bug was fixed with the version 3.1.0 😁
The feature was implemented 😌
