### ISSUE TITLE
URL are hard to read when highlighted

### ISSUE THREAD

**Issue by madebylydia** [icao/electron-vue#5]
Hey there! First of all, thank for making such a great theme! It is my favorite!

I would like to write this issue because I am having a bit of a hard time with URL when the text's cursor focus links. The green that applies on top of the blue-gray makes the link terrible to read. See the following GIF:
![Code_F5luYuGBVR](https://user-images.githubusercontent.com/61093863/155022509-e04acf12-2631-4f83-8eb4-c7f6c3573101.gif)

If you could make a slight change to either the URL's color when it get highlighted or simply change the highlight's color (If it doesn't affect the whole theme), that sure would make the theme much more convenient over URLs!
I'm kind surprised I haven't noticed this little issue earlier, so don't worry too much about this, it's not a really problematic issue. :)

I was unable to make a PR myself because I have no competence in making/editing a theme, so I'll leave the work for you!
Again, thank you very much for the theme that show me some love everyday! ❤️

**Comment by icao** [comment]
Hello @Predeactor 👋

an apology for reading your comment so late.
I understand the problem, I had not seen it before. It only happens at the time of clicking on any link. 
I was checking if I could change the color of the link when it is in focus, but currently VSCODE does not offer that configuration option, so I tried to correct the problem by making the background of the selection more transparent. I hope it solves the problem. 🤓👽

I thank you very much for the words and the patience to write to me 😁. It encourages me to continue developing the theme and is one more motivation to take it up again and keep improving it. I am currently working 👨‍💻 on a core to generate the default theme, with the new improvements that the vscode team is providing.
I will be working on it and also on releasing a version that better supports vue3. The new release is now available 👾🤖

Greetings and I hope you continue using ELECTRON VUE. 😁🤗
